version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-vocechat_server_1
      APP_PORT: 3000

  server:
    image: privoce/vocechat-server:v0.4.0@sha256:b97b87746680fb382251f327181405fb5e3f73eeb122ad31ca334db5fa58f48d
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/home/vocechat-server/data
