version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-thunderbird_web_1
      APP_PORT: 5800
  web:
    image: jlesage/thunderbird:v24.12.1@sha256:8dca275ff82b70393f11d43fb20f48aa5864e63539f882378e4d4ee6fdce235e
    restart: on-failure
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - DARK_MODE=1
      - WEB_AUDIO=1
      - WEB_AUTHENTICATION=0
      - WEB_LISTENING_PORT:5858
    volumes:
      - ${APP_DATA_DIR}/data:/config:rw
