version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-ferdium_server_1
      APP_PORT: 3333

  server:
    image: ghcr.io/ferdium/ferdium-server:2.0.10@sha256:2af65f3a79302b60a0f5079d6796388fa3b4840d3344968b69000c76f99fe46f
    environment:
      - NODE_ENV=production
      - APP_URL=http://umbrel-2.local:3333
      - DB_CONNECTION=sqlite
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=ferdium
      - DB_SSL=false
      - MAIL_CONNECTION=smtp
      - SMTP_HOST=127.0.0.1
      - SMTP_PORT=2525
      - MAIL_SSL=false
      - MAIL_USERNAME=username
      - MAIL_PASSWORD=password
      - MAIL_SENDER=noreply@ferdium.org
      - IS_CREATION_ENABLED=true
      - IS_DASHBOARD_ENABLED=true
      - IS_REGISTRATION_ENABLED=true
      - CONNECT_WITH_FRANZ=true
      - DATA_DIR=/data
      - JWT_USE_PEM=false
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/ferdium-database-vol:/data
      - ${APP_DATA_DIR}/data/ferdium-recipes-vol:/app/build/recipes
