---
  version: "2"
  
  volumes:
    app:
    db:
  
  services:
    app_proxy:
      environment:
        APP_HOST: denny-bookstack_app_1
        APP_PORT: 80
        PROXY_AUTH_ADD: "false"
    app:
      image: ghcr.io/linuxserver/bookstack:24.12.1@sha256:6736133cee386851f3e3579b73bf42897da2e055ce2578ec6649179f29569857
      environment:
        - PUID=1000
        - PGID=1000
        - APP_URL=http://umbrel.local:8875
        - DB_HOST=db
        - DB_PORT=3306
        - DB_USERNAME=bookstack
        - DB_PASSWORD=umbrelpass
        - DB_DATABASE=bookstackapp
        - APP_KEY=base64:agtE4ABZvOG9P7U7wM0Jzks+rTemAqlND6XUsyG/bHA=
      volumes:
        - ${APP_DATA_DIR}/data/bookstack_app_data:/config
      restart: on-failure
      depends_on:
        - db
  
    db:
      image: linuxserver/mariadb:11.4.4@sha256:fdf30e6b302688c290cef10ca24b80e6e25e93955bc6b64636777f06676a6c52
      environment:
        - PUID=1000
        - PGID=1000
        - MYSQL_ROOT_PASSWORD=mysqlrootpassword
        - TZ=Europe/Berlin
        - MYSQL_DATABASE=bookstackapp
        - MYSQL_USER=bookstack
        - MYSQL_PASSWORD=umbrelpass
      ports:
        - 3136:3306
      volumes:
        - ${APP_DATA_DIR}/data/bookstack_db_data:/config
      restart: on-failure

#solved: https://github.com/linuxserver/docker-bookstack/issues/235
