services:
  web:
    image: ghcr.io/hoarder-app/hoarder:0.21.0sha256:0fa320ade5d8f93195155e6df9f73f2ebd4176fe23210723a2d940c4715088f3 #Version in .env?
    container_name: Hoarder
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/hoarder/data:/data:rw
    ports:
      - 3888:3000 # ToDo: App-Proxy Konfiguartion
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: Optionales Feature
      DATA_DIR: /data
      NEXTAUTH_SECRET: 704pjzojQYCl4dgmriQedPK434FYMMxcDU4qKwBiAC #1
      MEILI_MASTER_KEY: YGBxRRBkTJiw5C82HZcuRumWqKRl1zJ99qijI2j85J #2

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: Chrome
    restart: on-failure
    command:
      - --no-sandbox
      - --disable-gpu
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222

  meilisearch:
    image: getmeili/meilisearch:v1.6@sha256:f858cf03fe9d6089a57cbf72b9d17fcf082738dd4a647e6515874dc428d44fce
    container_name: Meilisearch
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/hoarder/meili:/meili_data:rw
    environment:
     MEILI_MASTER_KEY: YGBxRRBkTJiw5C82HZcuRumWqKRl1zJ99qijI2j85J #2
     MEILI_NO_ANALYTICS: true
