version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-zipline_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  db:
    image: postgres:17.3@sha256:6e3358e46e34dae6c184f48fd06fe1b3dbf958ad5b83480031907e52b9ec2a7d
    volumes:
      - ./data/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: zipline
      POSTGRES_USER: ziplineuser
      POSTGRES_PASSWORD: ziplinepass
    restart: on-failure

  web:
    image: ghcr.io/diced/zipline:4.0.0@sha256:73351d7b653b2362895004398609adcfc60b2b7c9ad50b7cb488c8f4c36d4b3a
    environment:
      DATABASE_URL: postgresql://ziplineuser:ziplinepass@db:5432/zipline?schema=public
      CORE_SECRET: 3b449077187f1150082fb348796e97be22b57fefdbd4a7b18f575b51f65519b7
      CORE_PORT: 3000
      CORE_HOSTNAME: 0.0.0.0
      DATASOURCE_TYPE: local
      DATASOURCE_LOCAL_DIRECTORY: /data/files 
    volumes:
      - ./data/uploads:/zipline/uploads:rw
      - ./data/public:/zipline/public:rw
      - ./data/themes:/zipline/themes:rw
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: on-failure
