version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-photopea_web_1
      APP_PORT: 8080

  web:
    image: dennysubke/photopea:latest@sha256:56a1b0d64c6bd659e8254ae5dce6229bb28a7c055a0cb0d55efd01e1d30fb497
    restart: on-failure
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
