version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-glances_web_1
      APP_PORT: 61208
      PROXY_AUTH_ADD: "false"

  web:
    image: nicolargo/glances:4.3.0.8@sha256:b701ae99ee6ea402f56a7a94f2f374c5cca896d6e4d0cd8506d41b4a1b5adfe3
    environment:
      - TZ=Europe/Berlin
      - GLANCES_OPT=-w
    pid: host
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro