version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-mumble_web_1
      APP_PORT: 80

  server:
    image: mumblevoip/mumble-server:v1.5.634@sha256:11169b76bc418b414a3cb170694a4245ed51025fa0cba765886b28a8dff0dd97
    restart: on-failure
    user: "1000:1000"
    environment:
      - MUMBLE_CHOWN_DATA=true
      - MUMBLE_ACCEPT_UNKNOWN_SETTINGS=true
      - MUMBLE_SUPERUSER_PASSWORD=umbrel
    volumes:
      - ${APP_DATA_DIR}/data/mumble:/data:rw
    ports:
      - "64738:64738"
      - "64738:64738/udp"

  bridge:
    image: leoverto/mumble-web:latest@sha256:9590ed597b295adebe9be0b08a99e5dc8fe1651f8fcd90dc50038c0ec40366f3
    restart: on-failure
    user: "1000:1000"
    ports:
      - "8878:8080"
    environment:
      - MUMBLE_SERVER=server:64738

  web:
    image: nginx:1.27@sha256:124b44bfc9ccd1f3cedf4b592d4d1e8bddb78b51ec2ed5056c52d3692baebc19
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/www:/usr/share/nginx/html:ro
