version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-joplin_server_1
      APP_PORT: 22300
    networks:
      - joplin-network

  db:
    image: postgres:17.2@sha256:3267c505060a0052e5aa6e5175a7b41ab6b04da2f8c4540fc6e98a37210aa2d3
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/joplin/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: joplin
      POSTGRES_PASSWORD: joplinpass
      POSTGRES_DB: joplin
    networks:
      - joplin-network

  server:
    image: joplin/server:3.0.1-beta@sha256:52af57880c0e04a179107807e13ffb8868b31ea2cc86a2b04da42220facb7589
    restart: on-failure
    environment:
      APP_BASE_URL: http://umbrel-2.local:22300
      DB_CLIENT: pg
      POSTGRES_PASSWORD: joplinpass
      POSTGRES_DATABASE: joplin
      POSTGRES_USER: joplin
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      JOPLIN_EMAIL: admin@localhost
      JOPLIN_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - ${APP_DATA_DIR}/data/joplin:/var/lib/joplin
    networks:
      - joplin-network

networks:
  joplin-network:
    driver: bridge
