version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-donetick_web_1
      APP_PORT: 2021

  web:
    image: donetick/donetick:v0.1.37@sha256:c739ac617589ba3b7ec43c58153445bf16f5ccc4e24f14e77152bc071b78bcbe
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/donetick-data
      - ${APP_DATA_DIR}/config:/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
