version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-android_web_1
      APP_PORT: 6080

  web:
    image: budtmo/docker-android:emulator_13.0@sha256:93f68c6e4517ac15734eff8d65bda785fb9c5233fbf500cd4326a5bc103d484e
    restart: on-failure
    environment:
        - EMULATOR_DEVICE=Samsung Galaxy S10
        - WEB_VNC=true
    devices:
        - /dev/kvm
    volumes:
        - ${APP_DATA_DIR}/data/android-data:/home/androidusr

